[package]
name = "finales_funkeln"
version = "0.1.0"
authors = ["Boris-Chengbiao Zhou <bobo1239@web.de>"]
edition = "2018"

[dependencies]
rand = "0.6"
rand_xoshiro = "0.1.0"
rayon = "1.0.3"
indicatif = "0.11.0"

[features]
f64 = []
